export const USER_ROLE = {
  USER: 'user',
  ADMIN: 'admin'
};

export const VALIDATION_RULES = {
  USER: {
    NAME_MIN_LENGTH: 2,
    NAME_MAX_LENGTH: 100,
    EMAIL_MAX_LENGTH: 254,
    PHONE_MIN_LENGTH: 10,
    PHONE_MAX_LENGTH: 15
  },
  ADDRESS: {
    STREET_MIN_LENGTH: 5,
    STREET_MAX_LENGTH: 200,
    CITY_MIN_LENGTH: 2,
    CITY_MAX_LENGTH: 100,
    COUNTRY_MIN_LENGTH: 2,
    COUNTRY_MAX_LENGTH: 100,
    POSTAL_CODE_MIN_LENGTH: 3,
    POSTAL_CODE_MAX_LENGTH: 20
  }
}; 